[package]
name = "pwgen"
version = "0.1.0"
authors = ["skystar-p <skystar@skystar.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
clap = "2.33.3"
